import './globals.css'
import Header from './components/Header'

export const metadata = {
  title: 'Tes 123',
  description: 'Generated by Andreas',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-300">
        <Header />
        {children}
      </body>
    </html>
  )
}
